version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world. It is a great day!
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
