version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - jq/install
      - opsgenie/notify
orbs:
  jq: circleci/jq@1.9.1
  opsgenie: opsgenie/opsgenie@1.0.8
workflows:
  your-workflow:
    jobs:
      - build
